name: Test
on:
  push:
  workflow_dispatch:
concurrency:
  group: test
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          nix build -L -f default.nix ad1-tools

  test-flake:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          echo "ACTION_REPO=${{ env.ACTION_REPO }}" >> "$GITHUB_ENV"
          echo "ACTION_REF=${{ env.ACTION_REF }}" >> "$GITHUB_ENV"
        env:
          ACTION_REPO: ${{ github.action_repository }}
          ACTION_REF: ${{ github.action_ref }}
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          nix run github:$ACTION_REPO/$ACTION_REF
